notifications:
  email: false
language: node_js
node_js:
- node
sudo: required
services:
- docker
before_install:
- docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit
  bash
script:
- mkdir -p build/capnp_tool
- docker exec -it emscripten sh -c "cd build/capnp_tool && cmake -DCMAKE_INSTALL_PREFIX=install
  -DBUILD_TESTING=OFF ../../submodules/collab-vm-common/submodules/capnproto/ && cmake
  --build . --target install"
- mkdir -p build/collab-vm-web-app
- docker exec -it emscripten sh -c "cd build/collab-vm-web-app && emcmake cmake -DCAPNP_ROOT=../capnp_tool/install
  ../.. && cmake --build ."
- node ./node_modules/webpack-cli/bin/cli.js --config ./webpack.prod.js
- mv dist/ web-app/
- tar -czvf web-app.tar.gz web-app/
